### ISSUE TITLE
badger's batch writer should use upstream write batches

### ISSUE THREAD

**Issue by mvdan** [ChainSafe/chaindb#5]
In a codebase of mine, I saw huge performance wins by directly using https://pkg.go.dev/github.com/dgraph-io/badger/v2?tab=doc#DB.NewWriteBatch, instead of the current mechanism of first storing the operations in a `map[string][]byte`.

We do use a WriteBatch when flushing via the Write method, but making every operation go through a map first is IMO missing the point of using a write batch in the first place.

For example, it seems like badger's write batching flushes the writes to the database in large chunks. That is, writing a million values in a batch shouldn't mean keeping a million key-values in memory, as it might be flushing them in chunks of hundreds or thousands.

However, our current implementation always keeps the entire batch in memory, so it doesn't work well at all for large numbers of writes. I think that's the main purpose of batching writes in the first place, so I think we should remove the map entirely.

One feature we will lose because of this is the `Reset` method, which empties the batch. We can't implement this with "pure" write batches, because once a Put/Del has been done, it might already have been flushed to disk. I don't think we should support this kind of "undo" semantics in write batches.

If gossamer really needs that feature, I think you could continue using write batches, but keep the "reset" logic in your own code. That is, only use Database.NewBatch once the entire final set of writes has been computed. It has the same disadvantage about the memory usage as now, but it keeps write batches in this package fast, so it doesn't force the added complexity and slow-down for everyone else.

**Comment by noot** [comment]
This sounds good to me- gossamer doesn't use the batch writer yet, so it'll be good to get this in, then we can use it in gossamer.

**Comment by mvdan** [comment]
Great. I already have an implementation, so I'll just replace the current one in a PR.
